Develop
VadimLitau/Algososh pull request #8
Opened 2022-11-22 16:32 UTC by VadimLitau

2022-11-22 18:19 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Работа проделана огромная.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Реализованы все алгоритмы.

### **Но есть несколько замечаний, которые нужно исправить:**

- По чек-листу: функции, которые реализуют работу алгоритмов и не взаимодействуют с компонентом, должны быть вынесены в отдельные файлы utils.ts в папке соответствующего компонента;

- По чек-листу: классы, описывающие работу структур данных, стоит вынести в отдельные файлы в папке соответствующего компонента. Видел у вас есть это, но почему-то все классы дублируются в `list-page/utils.ts`.

- Вынесите тайминги в константы (Заметил, что у вас они уже есть, но вы не везде их используйте). Например: `await setInterval(500); // 500 нужно вынести к константу`.

- "Магические" значения лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE. Не стал отмечать везде места в коде (Было бы немало замечаний, но если нужно напишите в комментарии, помогу вам!), просто вынесите значения:

  - min/max (длина вводимого слова, количество элементов массива для сортировки, и т.д)
  - некоторые особенные тайминги, если такие есть.
  - некоторые особенные тайминги, если такие есть.

- Строка:

  - кнопки включения визуализации алгоритма должны быть активны, только если введены валидные данные и структура данных допускает это действие в данный момент;

- Сортировка массива:

  - Это круто, что у вас есть loading на кнопках, но лучше делать loading только на той кнопке, которую нажали, а остальные делать `disabled`.

- Стек:

  - Во время анимации алгоритма на активной кнопке должен отображаться прелоадер, остальные кнопки и поля ввода - неактивны (состояние disabled), до завершения работы алгоритма;

  - Отцентрировать надпись над кружком: https://yadi.sk/d/jKH6tScrdWCORg;

- Очередь:

  - Отцентровать надписи над кружком: https://yadi.sk/d/bmLyGmgizI28nw;

- Связный список:

  - Поправить вёрстку, отцентрировать текст и выровнять строку по середине. https://yadi.sk/d/SiI4oUhizgt0Fw.
    Как правильно: https://yadi.sk/d/zj35FES2NOPTtQ

  - При удалении по индексу у вас появляться нолик (вместо надписи Tail), а должно появляться значение которое удаляется.

    - Ваш вариант: https://disk.yandex.ru/d/4agRfpzLSFRmbg.
    - Как должно быть: https://disk.yandex.ru/d/RSKkRNjoe1NxWg;

    А также поправьте вёрстку, чтобы элементы не прыгали :)

    Еще заметил что у вас есть баг, если удалять нулевой элемент, некоторые значения просто пропадают (Показано в видео).

  - Нужно давать кнопкам `disabled`, когда введёный индекс превышает или равен количеству элементов списка: https://yadi.sk/d/Ds24333KxBj8Ew.

  - Если список остаётся пустым, то нужно запретить удаление элементов, иначе у вас может возникнуть ошибка: https://yadi.sk/d/66_HC9E6kGv4QQ;

- Приложение не должно содержать `console.log` и `debugger-ов`.

### **Сделает код лучше:**

- При использовании return внутри `if`, оператор `else` можно опустить, т.к. если `if` выполнится, то будет возврат из функции и код под блоком `if` выполнен не будет:

  ```js
  if (someCondition) {
    return value;
  }
  return data;
  ```

  Такой подход называется "ранний возврат" https://habr.com/ru/post/348074/

- Лучше реализовывать удаление таймера/интервала при размонтировании компонента, иначе возможны ошибки/баги когда компонент размонтируется, а таймер всё равно сработает.

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2022-11-22 18:19 UTC, ArslanMustafin commented on src/components/fibonacci-page/fibonacci-page.tsx
> +    let series: any = new Array(item);
**Надо исправить:**

если переменная не перезаписывается, то её следует объявлять как `const`, обратите внимание, что добавление элемента в массив или изменение свойства объект не являются перезаписью самой переменной, а изменяют только их внутреннее состояние, поэтому их так же нужно объявлять как `const`

`new Array(item)` - не очень хорошо так делать (есть вероятность неправильно использовать индексы, забрать лишнюю память и т.д.), если у вас не будет идей как это обыграть, попробую помочь вам в следующем ревью.

2022-11-22 18:19 UTC, ArslanMustafin commented on src/components/fibonacci-page/fibonacci-page.tsx
> +  const fibonacciSequence = (item: number) => {
**Надо исправить:**

По чек-листу у вас должна быть функция `getFibonacciNumbers`, которая принимает количество чисел как параметр и возвращает требуемый массив чисел последовательности Фибоначчи;

А также она должна быть в файлике `utils.ts` в папке алгоритма.

2022-11-22 18:19 UTC, ArslanMustafin commented on src/components/fibonacci-page/fibonacci-page.tsx
> +      }, 500 * i);
**Надо исправить:**

Вынесите тайминги в константы (Заметил, что у вас они уже есть, но вы их практически нигде не используйте).

2022-11-22 18:19 UTC, ArslanMustafin commented on src/components/fibonacci-page/fibonacci-page.tsx
> +          <p className={style.inputSubtext}>Максимальное число — 19</p>
**Надо исправить:**

"Магические" значения лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE.

2022-11-22 18:19 UTC, ArslanMustafin commented on src/components/fibonacci-page/fibonacci-page.tsx
> +          disabled={values.fibonacci < 1 || values.fibonacci > 19}
**Надо исправить:**

`1 и 19`

"Магические" значения лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE.

2022-11-22 18:19 UTC, ArslanMustafin commented on src/components/list-page/list-page.tsx
> +    setLoaderState({
**Можно лучше:** 

Возможно стоит вынести в константу некоторые состояния и просто их переиспользовать) 
Ну или в кранейм случае у нас всегда есть функциональное обновление и rest оператор `...` ))

https://ru.reactjs.org/docs/hooks-reference.html#functional-updates

2022-11-22 18:19 UTC, ArslanDev666 commented on src/components/list-page/utils.ts
> +export class LinkedList<T> implements ILinkedList<T> {
**надо исправить:**

по чек-листу: класс LinkedList должен принимать в качестве опционального параметра конструктора массив элементов для инициализации списка;

2022-11-22 18:19 UTC, ArslanDev666 commented on src/components/list-page/utils.ts
> +interface ILinkedList<T> {
**Можно лучше:** 

По чек-листу: там немного больше методов `prepend, append, addByIndex, deleteByIndex, deleteHead, deleteTail и toArray`)) но думаю если всё прекрасно работает, то не стоит это трогать. Но если у вас будет желание, то добавьте методы из чек-листа))

2022-11-22 18:19 UTC, ArslanDev666 commented on src/components/string/string.tsx
> +          console.log(count.start, count.end);
**Надо исправить:**

В приложении не должно быть console.log или дебаггеров.

2022-11-22 18:19 UTC, ArslanDev666 commented on src/components/fibonacci-page/fibonacci-page.tsx
> +          console.log(i);
**Надо исправить:**

В приложении не должно быть console.log или дебаггеров.

2022-11-22 18:19 UTC, ArslanDev666 commented on src/components/list-page/utils.ts
> +      console.log("Enter a valid index");
**Надо исправить:**

В приложении не должно быть console.log или дебаггеров.

2022-11-22 18:19 UTC, ArslanDev666 commented on src/components/list-page/utils.ts
> +    } else {
**Можно лучше:**

Здесь и в похожих местах

При использовании return внутри `if`, оператор `else` можно опустить, т.к. если `if` выполнится, то будет возврат из функции и код под блоком `if` выполнен	не будет:
```js
if (someCondition) {
  return value;
}

return data;
```
Такой подход называется "ранний возврат" https://habr.com/ru/post/348074/

2022-11-23 11:21 UTC, VadimLitau commented on src/components/list-page/list-page.tsx
> +    setLoaderState({
Улучшить однозначно можно и нужно, добавил себе эту задачу в список "сделать позже" =)

2022-11-24 02:10 UTC, ArslanDev666 commented on src/components/list-page/utils.ts
> +  constructor(defaultValues?: T[] | undefined) {
**Можно лучше:**
Тут можно не указывать дополнительно `| undefined`, вы ведь поставили `?`, а значит параметр необязательный.

2022-11-24 02:29 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Практически все замечания с прошлого ревью были исправлены.

### **Вы молодец!**

### **Но есть несколько замечаний, которые нужно исправить:**

- Отметил в коде "Магические" значения.

- Стек:

  - Во время анимации алгоритма на активной кнопке должен отображаться прелоадер, остальные кнопки и поля ввода - неактивны (состояние disabled), до завершения работы алгоритма; Например как вы сделали в алгоритме `Связный список`.

  - После работы алгоритма, у вас не пропадает выделение с добавленного элемента: https://disk.yandex.ru/d/jMTWmo5PqzCZUw.

- Связный список:

  - Если список остаётся пустым, то нужно запретить удаление элементов, иначе у вас может возникнуть ошибка: https://yadi.sk/d/66_HC9E6kGv4QQ; Либо можно просто запретить удалять последний элемент)

* Приложение не должно содержать `console.log` и `debugger-ов`. `components/list-page/utils.ts`

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2022-11-24 02:29 UTC, ArslanDev666 commented on src/components/list-page/utils.ts
> +  constructor(defaultValues?: T[] | undefined) {
**Можно лучше:**
Тут можно не указывать дополнительно `| undefined`, вы ведь поставили `?`, а значит параметр необязательный.

2022-11-24 02:29 UTC, ArslanDev666 commented on src/components/list-page/list-page.tsx
> +            maxLength={4}
**Надо исправить:**

Магические значение лучше вынести в константу) и переиспользовать.

2022-11-24 02:29 UTC, ArslanDev666 commented on src/components/queue-page/queue-page.tsx
> +    }, 500);
**Надо исправить:**

тайминги лучше вынести в константу) и переиспользовать.

2022-11-24 02:29 UTC, ArslanDev666 commented on src/components/queue-page/queue-page.tsx
> +    const queue = new Queue<string>(7);
**Надо исправить:**

Магические значение лучше вынести в константу) и переиспользовать.

2022-11-24 02:29 UTC, ArslanDev666 commented on src/components/queue-page/queue-page.tsx
> +    }, 500);
**Надо исправить:**

Тайминги лучше вынести в константу) и переиспользовать.

2022-11-24 02:29 UTC, ArslanDev666 commented on src/components/queue-page/queue-page.tsx
> +              maxLength={4}
**Надо исправить:**

Магические значение лучше вынести в константу) и переиспользовать.

2022-11-24 02:29 UTC, ArslanDev666 commented on src/components/stack-page/stack-page.tsx
> +    }, 1000);
**Надо исправить:**

Тайминги лучше вынести в константу) и переиспользовать.

2022-11-24 02:29 UTC, ArslanDev666 commented on src/components/stack-page/stack-page.tsx
> +    }, 1000);
**Надо исправить:**

Тайминги лучше вынести в константу) и переиспользовать.

2022-11-24 02:29 UTC, ArslanDev666 commented on src/components/string/string.tsx
> +  const [count, setCount] = useState({ start: -1, end: 99, loader: false });
**Надо исправить:**

Магические значение лучше вынести в константу) и переиспользовать.

2022-11-24 02:29 UTC, ArslanDev666 commented on src/components/string/string.tsx
> +    setCount({ ...count, start: -1, end: 12, loader: true });
**Надо исправить:**

Магические значение лучше вынести в константу) и переиспользовать.

2022-11-24 02:29 UTC, ArslanDev666 commented on src/components/string/string.tsx
> +        end: 12,
**Надо исправить:**

Магические значение лучше вынести в константу) и переиспользовать.

2022-11-24 02:29 UTC, ArslanDev666 commented on src/components/string/string.tsx
> +            maxLength={11}
**Надо исправить:**

Магические значение лучше вынести в константу) и переиспользовать.

2022-11-24 02:29 UTC, ArslanDev666 commented on src/components/string/string.tsx
> +          <p className={style.inputSubtext}>Максимум — 11 символов</p>
**Надо исправить:**

Магические значение лучше вынести в константу) и переиспользовать.

2022-11-24 03:51 UTC, VadimLitau commented on src/components/string/string.tsx
> +          <p className={style.inputSubtext}>Максимум — 11 символов</p>
Я вот читаю все эти комментарии и мне прям стыдно становится)))Приз за самого внимательного студента явно уйдет ко мне)

2022-11-25 02:48 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Все замечания с прошлого ревью были исправлены.

### **Вы молодец!🔥 Работа принята, удачи в дальнейшем обучении!**

2022-12-13 05:49 UTC, merged